apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: lukke0/projeto_docker
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: database-service  
        - name: DB_PORT
          value: "3306"
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort